image: docker.internal.33across.com/ruby:1.9.3-p551
before_script:
  - source /usr/local/rvm/scripts/rvm
  - bundle install #--path vendor/bundle
#  #hardcoding below to retain 1.9.3-compatible versions
#  - gem install -v "< 2" rack #1.6.9 ok, 2.0 requires ruby 2.2.2
#  - gem install -v "< 2.5" addressable #2.4.0 ok, 2.5.0 requires public_suffix, which requires ruby 2.1
#  - gem install -v "< 2.2.1" jeweler #2.1.2 ok, 2.2.1 requires ruby 2.2.0
#  - gem install -v "< 5" activesupport #4.2 ok, 5.0 wants ruby 2.2.2
#  - gem install yajl-ruby shoulda
  - rm Gemfile #funky interaction between Gemfile detection and jeweler
test:
  stage: test
  
  script:
    - rake
  cache:
    paths:
      - vendor/bundle
  artifacts:
    paths:
      - coverage/
    expire_in: 52 weeks

build:
  stage: build
  script:
    - "gem build *.gemspec"
  cache:
    paths:
      - vendor/bundle
  artifacts:
    paths:
      - "*.gem"
  only:
    - tags
      
publish:
  stage: deploy
  before_script:
    - echo "Skipping global before_script"
    - source /usr/local/rvm/scripts/rvm
  script:
    - "gem nexus --url \"https://nexus.internal.33across.com/repository/ruby\" --credential \"$NEXUS_USERNAME:$NEXUS_PASSWORD\" *.gem"
  dependencies:
    - build
  only:
    - tags
